/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.cs2263;

import javafx.application.Application;
import javafx.stage.Stage;



public class App extends Application {



    @Override
    public void start(Stage primaryStage) throws Exception {

        primaryStage.setTitle ("First JavaFX Application");

        primaryStage.show();
    }


    public static void main(String[] args){
        Application.launch(args);

    }

}